#! /bin/bash

# a small wrapper to make running and viewing the output of daily scripts easier
# I used to run this: python <script>.py 500 500 out.png && icat out.png
# but I started abusing the 3rd param to pass extra data to the script since I always name the files out.png

if [ $# -eq 4 ]
then
	# check if out.png exists if it does delete it
	if [ -f out.png ] 
	then
		rm out.png
	fi
	# pass the commands through to the selected script
	python $1 $2 $3 $4 && kitty +kitten icat out.png
else
	echo "usage: run <script> <width> <height> <extra>"
fi
